### PR TITLE
feat: upgrade to postgres 15 and allow the use of schemas

### PR DESCRIPTION
**Pull request by lspgn**
Upgrades to Postgres 15. [There was a change for the public schema permissions](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATTERNS).
Adding the support of a schema when running migrations.

Small nit on the EOF.

Let me know what you think. And thank you for making this repository.

### CODE REVIEW

**Comment by dpraul** [comment]
Fantastic, thanks for the contribution! Worked well for me locally, although I haven't put it through the ringer yet. I was holding on updating to PG 15 because I hadn't verified DAViCal's official support for PG 15 yet, but I see now reason it shouldn't work. Have you been running this yourself for any amount of time?

**Review by georgefintechstudioscom — APPROVED** [review]
Looks OK to me.  I had to read up on the schemas, but this pattern is a simple one and looks secure.

**Comment by lspgn** [comment]
@dpraul 
> Have you been running this yourself for any amount of time?

I have not, unfortunately.
I'm deploying it from scratch after a change of workflow so I was trying to get the latest versions in.

**Comment by loopway** [comment]
is this going to be merged? DAViCal version 1.1.12 has been released in the meantime and postgres 15 is mentioned in the release notes: https://gitlab.com/davical-project/davical/-/blob/master/ChangeLog

**Review by dpraul — APPROVED** [review]
Sorry for the late review, I was finally able to do some testing to verify that this works as-expected. Thanks so much for contribution!

**Pull request merged**
